'use client'

import { useRef, useState } from 'react'
import { AlertTriangle, Check, ChevronRight, ClipboardCheck, FileCheck2, FilePlus2, Fingerprint, FolderOpen, LockKeyhole, Menu, Search, ShieldAlert, ShieldCheck, Upload, UserRound, X } from 'lucide-react'

type Role = 'Investigating Officer' | 'Supervisory Officer' | 'Legal Reviewer' | 'Auditor'
type View = 'Dashboard' | 'Cases' | 'Documents' | 'Transfers' | 'Integrity' | 'Audit'

const nav: View[] = ['Dashboard', 'Cases', 'Documents', 'Transfers', 'Integrity', 'Audit']
const baseEvents = [
  ['DOCUMENT_INGESTED', 'Forensic_Report.pdf · V1', 'Officer Ravi Kumar', '10:32 AM'],
  ['TRANSFER_REQUESTED', 'IO → Legal Reviewer', 'Officer Ravi Kumar', '10:41 AM'],
  ['TRANSFER_APPROVED', 'Version-scoped access granted', 'Supervisor', '10:44 AM'],
  ['INTEGRITY_VERIFICATION', 'Hash mismatch detected', 'System verification', '10:47 AM'],
]

function Badge({ children, tone = 'blue' }: { children: React.ReactNode; tone?: 'blue' | 'green' | 'red' | 'amber' | 'gray' }) { return <span className={`badge ${tone}`}>{children}</span> }
function Metric({ label, value, detail, icon, tone = 'blue' }: { label: string; value: string; detail: string; icon: React.ReactNode; tone?: string }) { return <article className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article> }

export default function NyayaChain() {
  const [view, setView] = useState<View>('Dashboard')
  const [role, setRole] = useState<Role>('Investigating Officer')
  const [tampered, setTampered] = useState(false)
  const [verified, setVerified] = useState(false)
  const [transfer, setTransfer] = useState<'pending' | 'approved' | 'rejected' | null>(null)
  const [modal, setModal] = useState<'upload' | 'transfer' | null>(null)
  const [file, setFile] = useState<File | null>(null)
  const [uploadError, setUploadError] = useState('')
  const [uploadComplete, setUploadComplete] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const isSupervisor = role === 'Supervisory Officer'
  const canUpload = role === 'Investigating Officer'
  const canTransfer = role === 'Investigating Officer' && !tampered
  const simulateAttack = () => { setTampered(true); setVerified(false); setView('Integrity') }
  const chooseFile = (f?: File) => {
    setUploadError('')
    if (!f) return
    const allowed = ['application/pdf', 'image/jpeg', 'image/png']
    if (!allowed.includes(f.type)) {
      setUploadError('Unsupported file type. Choose a PDF, JPG, or PNG file.')
      return
    }
    if (f.size > 25 * 1024 * 1024) {
      setUploadError('File is too large. Maximum upload size is 25 MB.')
      return
    }
    setFile(f)
  }
  const pageTitle = view === 'Dashboard' ? 'SECURE EVIDENCE OPERATIONS' : view.toUpperCase()

  return <div className="app"><header className="topbar"><div className="brand"><span className="brand-mark"><Fingerprint /></span><div><strong>NyayaChain</strong><small>TAMPER-EVIDENT CUSTODY</small></div></div><nav>{nav.map(item => <button key={item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{item}</button>)}</nav><div className="profile"><div><b>Officer Ravi Kumar</b><small>{role}</small></div><span className="avatar">RK</span><button className="icon-btn" aria-label="Open menu"><Menu /></button></div></header>
    <main className="main"><div className="heading"><div><p className="kicker">{view === 'Dashboard' ? 'SECURE EVIDENCE OPERATIONS' : 'NYAYACHAIN / ' + view}</p><h1>{pageTitle}</h1><p className="subtitle">{view === 'Dashboard' ? 'Monitor assigned cases and maintain a tamper-evident chain of custody.' : 'Technical integrity and custody evidence for assigned case records.'}</p></div><div className="role-control"><label>Demo role</label><select value={role} onChange={e => setRole(e.target.value as Role)}>{['Investigating Officer', 'Supervisory Officer', 'Legal Reviewer', 'Auditor'].map(r => <option key={r}>{r}</option>)}</select></div></div>
      {view === 'Dashboard' && <><section className="metrics"><Metric label="Assigned cases" value="12" detail="2 updated today" icon={<FolderOpen />} /><Metric label="Active documents" value="48" detail="47 verified · 1 restricted" icon={<FileCheck2 />} tone="green" /><Metric label="Pending transfers" value="03" detail="Requires review" icon={<ClipboardCheck />} tone="amber" /><Metric label="Integrity alerts" value={tampered ? '02' : '01'} detail="Action required" icon={<ShieldAlert />} tone="red" /></section><div className="dashboard-grid"><CasePanel onOpen={() => setView('Cases')} /><IntegrityPanel tampered={tampered} onReview={() => setView('Integrity')} /><Custody events={tampered ? [...baseEvents, ['INTEGRITY_ALERT', 'SHA-256 mismatch · version restricted', 'System', '10:47 AM']] : baseEvents} /></div></>}
      {view === 'Cases' && <Cases onOpen={() => setView('Documents')} />}
      {view === 'Documents' && <Documents tampered={tampered} onVerify={() => { setVerified(true); setView('Integrity') }} onUpload={canUpload ? () => setModal('upload') : undefined} />}
      {view === 'Transfers' && <Transfers role={role} transfer={transfer} onRequest={canTransfer ? () => { setTransfer('pending'); setModal(null) } : undefined} onApprove={isSupervisor ? () => setTransfer('approved') : undefined} />}
      {view === 'Integrity' && <Integrity tampered={tampered} verified={verified} onVerify={() => setVerified(true)} onAttack={simulateAttack} />}
      {view === 'Audit' && <Audit tampered={tampered} />}
      {uploadComplete && <div className="upload-toast" role="status"><Check /> Document secured and added to the custody record.</div>}
    </main>
    {modal && <div className="overlay" onMouseDown={() => setModal(null)}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e => e.stopPropagation()}><div className="modal-head"><div><h2>{modal === 'upload' ? 'Upload secured document' : 'Request version transfer'}</h2><p>All actions are recorded to the audit trail.</p></div><button className="icon-btn" onClick={() => setModal(null)} aria-label="Close"><X /></button></div>{modal === 'upload' ? <><input ref={inputRef} hidden type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e => chooseFile(e.target.files?.[0])} /><button type="button" className={`dropzone ${file ? 'selected' : ''}`} onClick={() => inputRef.current?.click()} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); inputRef.current?.click() } }} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); chooseFile(e.dataTransfer.files[0]) }}>{file ? <><FileCheck2 /><b>{file.name}</b><span>{(file.size / 1024 / 1024).toFixed(2)} MB selected · click to replace</span></> : <><Upload /><b>Drop evidence file here</b><span>or click to browse · PDF, JPG, PNG up to 25 MB</span></>}</button>{uploadError && <p className="upload-error" role="alert">{uploadError}</p>}<label className="field">Document description<input placeholder="e.g. Forensic report" /></label></> : <div className="transfer-form"><p><b>Document</b> Forensic_Report.pdf · V1</p><p><b>From</b> Officer Ravi Kumar</p><p><b>To</b> Legal Reviewer</p><label className="field">Reason<input defaultValue="Legal review required" /></label></div>}<div className="modal-actions"><button className="button" onClick={() => setModal(null)}>Cancel</button><button className="button primary" disabled={modal === 'upload' && !file} onClick={() => { if (modal === 'transfer') { setTransfer('pending') } else { setUploadComplete(true) }; setModal(null); setFile(null); setUploadError('') }}>{modal === 'upload' ? 'Secure document' : 'Submit request'}</button></div></section></div>}
  </div>
}

function CasePanel({ onOpen }: { onOpen: () => void }) { return <section className="card case-panel"><div className="card-head"><div><p className="overline">ACTIVE CASE</p><h2>HYD-CYB-2026-0147</h2></div><Badge tone="green">ACTIVE</Badge></div><div className="case-content"><h3>Cyber Fraud — Bank Account Hacking</h3><div className="details"><span>Assigned officer<strong>Ravi Kumar</strong></span><span>Documents<strong>08 secured files</strong></span><span>Priority<strong><Badge tone="red">HIGH</Badge></strong></span></div><button className="button primary" onClick={onOpen}>View case <ChevronRight /></button></div></section> }
function IntegrityPanel({ tampered, onReview }: { tampered: boolean; onReview: () => void }) { return <section className="card"><div className="card-head"><div><p className="overline">INTEGRITY ALERTS</p><h2>{tampered ? '2 open alerts' : '1 open alert'}</h2></div><ShieldAlert className="red-icon" /></div><div className="alert-row"><span className="alert-mark"><AlertTriangle /></span><div><b>Forensic_Report.pdf</b><p>INTEGRITY MISMATCH · 2 minutes ago</p></div><Badge tone="red">RESTRICTED</Badge></div><button className="button outline" onClick={onReview}>Review alert</button></section> }
function Custody({ events }: { events: string[][] }) { return <section className="card custody"><div className="card-head"><div><p className="overline">RECENT CUSTODY ACTIVITY</p><h2>Audit trail</h2></div><Badge>HASH-CHAINED</Badge></div><div className="activity">{events.map((e, i) => <div className="activity-item" key={e[0]}><span className={i > 2 ? 'dot red' : 'dot'}>{i > 2 ? <AlertTriangle /> : <Check />}</span><div><b>{e[0]}</b><strong>{e[1]}</strong><small>{e[2]} · {e[3]}</small></div></div>)}</div></section> }
function Cases({ onOpen }: { onOpen: () => void }) { return <section className="card table-card"><div className="card-head"><div><p className="overline">ASSIGNED CASES</p><h2>Cases</h2></div><div className="search"><Search /><input placeholder="Search case ID" /></div></div><table><thead><tr><th>Case ID</th><th>Case name</th><th>Officer</th><th>Files</th><th>Priority</th><th>Status</th><th>Updated</th><th /></tr></thead><tbody><tr><td className="mono">HYD-CYB-2026-0147</td><td><b>Cyber Fraud — Bank Account Hacking</b></td><td>Ravi Kumar</td><td>8</td><td><Badge tone="red">HIGH</Badge></td><td><Badge tone="green">ACTIVE</Badge></td><td>12 min ago</td><td><button className="text-button" onClick={onOpen}>Open</button></td></tr></tbody></table></section> }
function Documents({ tampered, onVerify, onUpload }: { tampered: boolean; onVerify: () => void; onUpload?: () => void }) { return <section className="card document-page"><div className="card-head"><div><p className="overline">CASE DOCUMENTS / HYD-CYB-2026-0147</p><h2>Evidence versions</h2></div>{onUpload && <button className="button primary" onClick={onUpload}><FilePlus2 /> Upload document</button>}</div><div className="document"><div className="file-icon"><FileCheck2 /></div><div className="document-main"><div className="document-title"><div><h3>Forensic_Report.pdf</h3><p>Registered 26 Sep 2026 by Ravi Kumar</p></div><Badge tone={tampered ? 'red' : 'green'}>{tampered ? 'RESTRICTED' : 'VALID'}</Badge></div><div className="version-grid"><div><span>Version</span><b>V1</b></div><div><span>SHA-256</span><b className="mono">8f3a...91cd <button className="copy">Copy</button></b></div><div><span>Size</span><b>4.8 MB</b></div></div><div className="document-actions"><button className="button outline" onClick={onVerify}><ShieldCheck /> Verify integrity</button><button className="button outline">View custody</button></div></div></div><div className="previous"><LockKeyhole /> Previous versions are preserved. V2 is a successor version and never replaces V1.</div></section> }
function Transfers({ role, transfer, onRequest, onApprove }: { role: Role; transfer: string | null; onRequest?: () => void; onApprove?: () => void }) { return <section className="card transfer-page"><div className="card-head"><div><p className="overline">VERSION-SCOPED ACCESS</p><h2>Transfer workflow</h2></div>{onRequest && <button className="button primary" onClick={onRequest}>Request transfer</button>}</div><div className="flow"><span>Investigating Officer</span><ChevronRight /><span>Transfer request</span><ChevronRight /><span className={transfer === 'approved' ? 'approved' : 'pending'}>{transfer?.toUpperCase() || 'PENDING'}</span><ChevronRight /><span>Legal Reviewer</span></div><div className="transfer-item"><div><h3>Forensic_Report.pdf <Badge>V1</Badge></h3><p>Officer Ravi Kumar → Legal Reviewer · Legal review required</p></div>{transfer === 'approved' ? <Badge tone="green">APPROVED</Badge> : <Badge tone="amber">PENDING</Badge>}{role === 'Legal Reviewer' && transfer !== 'approved' && <p className="denied">Access denied — supervisor approval required.</p>}{onApprove && transfer === 'pending' && <button className="button primary" onClick={onApprove}>Approve transfer</button>}</div></section> }
function Integrity({ tampered, verified, onVerify, onAttack }: { tampered: boolean; verified: boolean; onVerify: () => void; onAttack: () => void }) { return <section className="integrity-page"><div className={`security-banner ${tampered ? 'danger' : 'safe'}`}><div>{tampered ? <ShieldAlert /> : <ShieldCheck />}<div><b>{tampered ? 'INTEGRITY VIOLATION DETECTED' : 'SHA-256 INTEGRITY STATUS'}</b><p>{tampered ? 'Stored file content differs from the registered SHA-256 hash.' : 'No unreviewed integrity violations on assigned files.'}</p></div></div><Badge tone={tampered ? 'red' : 'green'}>{tampered ? 'RESTRICTED' : 'VALID'}</Badge></div><div className="integrity-grid"><section className="card verification"><div className="card-head"><div><p className="overline">VERIFICATION RESULT</p><h2>Forensic_Report.pdf — V1</h2></div><button className="button outline" onClick={onVerify}>Verify integrity</button></div><div className="checks"><p><Check /> File exists</p><p><Check /> Custody chain loaded</p><p className={tampered ? 'failed' : 'muted'}>{tampered ? '✕' : '○'} SHA-256 {tampered ? 'mismatch' : 'not yet verified'}</p><p><Check /> Alert created</p></div><div className={`result ${tampered ? 'danger' : verified ? 'safe' : 'pending'}`}><b>{tampered ? 'RESTRICTED' : verified ? 'VALID' : 'UNDER REVIEW'}</b><span>{tampered ? 'Document integrity verification failed. Further content access and transfer are blocked pending supervisory review.' : 'Registered and computed hashes match.'}</span></div></section><section className="card demo"><div className="card-head"><div><p className="overline">DEMO MODE</p><h2>Simulate cyber attack</h2></div><AlertTriangle className="amber-icon" /></div><p>Change the demo file state to show how a tamper-evident alert restricts content and transfer access.</p><button className="button danger-button" onClick={onAttack}>Simulate cyber attack</button></section></div></section> }
function Audit({ tampered }: { tampered: boolean }) { const rows = [...baseEvents, ...(tampered ? [['INTEGRITY_ALERT', 'SHA-256 mismatch', 'System', '10:47 AM']] : [])]; return <section className="card table-card"><div className="card-head"><div><p className="overline">READ-ONLY RECORD</p><h2>Audit trail</h2></div><div className="filters"><select><option>All event types</option></select><select><option>All statuses</option></select></div></div><table><thead><tr><th>Event type</th><th>Record</th><th>Actor</th><th>Time</th><th>Status</th></tr></thead><tbody>{rows.map(r => <tr key={r[0]}><td className="mono">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]} · 26 Sep 2026</td><td><Badge tone={r[0] === 'INTEGRITY_ALERT' ? 'red' : 'green'}>{r[0] === 'INTEGRITY_ALERT' ? 'ALERT' : 'RECORDED'}</Badge></td></tr>)}</tbody></table></section> }
