"use client"

import { useRef, useState } from "react"
import { AlertTriangle, ArrowUpRight, Check, CheckCircle2, Clock3, FileCheck2, FilePlus2, Fingerprint, FolderOpen, LogOut, ShieldCheck, Upload, UserRound, X } from "lucide-react"

type Modal = "upload" | "transfer" | null
const events = [
  { seq: 1, action: "DOCUMENT_INGESTED", actor: "Officer Ravi Kumar", role: "Investigating Officer", time: "14 Sep 2026, 09:42 UTC", hash: "a8f4d2c1...7b91", prev: "Genesis block", tone: "green" },
  { seq: 2, action: "TRANSFER_REQUESTED", actor: "Officer Ravi Kumar", role: "Investigating Officer", time: "14 Sep 2026, 10:05 UTC", hash: "c19e0b44...42ea", prev: "a8f4d2c1...7b91", tone: "blue" },
  { seq: 3, action: "TRANSFER_APPROVED", actor: "Adv. Meera Shah", role: "Public Prosecutor", time: "14 Sep 2026, 10:12 UTC", hash: "e3b0c442...924", prev: "c19e0b44...42ea", tone: "blue" },
]
function Stat({ icon, label, value, trend, alert }: { icon: React.ReactNode; label: string; value: string; trend: string; alert?: boolean }) { return <div className="stat-card"><div className="stat-label"><span>{label}</span><span className={`stat-icon ${alert ? "alert" : ""}`}>{icon}</span></div><div className="stat-number">{value}</div><div className="stat-trend">{trend}</div></div> }
export default function Dashboard() {
  const [modal, setModal] = useState<Modal>(null); const [tab, setTab] = useState("Case overview"); const [verified, setVerified] = useState(true)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const closeModal = () => { setModal(null); setSelectedFile(null) }
  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (file && file.size <= 25 * 1024 * 1024) setSelectedFile(file)
    else if (file) event.target.value = ""
  }
  const secureDocument = () => { if (selectedFile) closeModal() }
  return <div className="shell"><header className="topbar"><div className="brand"><span className="brand-mark"><Fingerprint /></span>NyayaChain</div><div className="user-area"><div className="user-copy"><strong>Officer Ravi Kumar</strong><span>Investigating Officer · Cyber Crime Unit</span></div><div className="avatar">RK</div><button className="logout" aria-label="Log out"><LogOut /> Log out</button></div></header>
    <main className="content"><p className="eyebrow">Secure evidence operations</p><h1 className="page-title">Good morning, Officer Ravi</h1><p className="intro">Monitor your assigned cases and maintain an immutable chain of custody.</p>
      <section className="stats"><Stat icon={<FolderOpen />} label="Total assigned cases" value="12" trend="+2 this month" /><Stat icon={<FileCheck2 />} label="Active documents" value="48" trend="All integrity checks passed" /><Stat icon={<Clock3 />} label="Pending transfers" value="03" trend="Requires your review" /><Stat icon={<AlertTriangle />} label="Open integrity alerts" value="01" trend="Action required" alert /></section>
      <section className="grid-main"><article className="card case-card"><div className="card-header"><div><p className="card-title">Active case</p><p className="card-subtitle">Last updated 12 minutes ago</p></div><span className="badge green"><CheckCircle2 /> ACTIVE</span></div><div className="card-body"><div className="case-id">HYD-CYB-2026-0147</div><div className="case-name">Cyber Fraud — Bank Account Hacking</div><div className="case-row"><div><span>Lead officer</span><strong>Ravi Kumar</strong></div><div><span>Documents</span><strong>08 secured files</strong></div><div><span>Priority</span><strong><span className="badge red">HIGH</span></strong></div></div><div className="actions"><button className="btn primary" onClick={() => setTab("Case overview")}>View case documents <ArrowUpRight /></button><button className="btn ghost" onClick={() => setModal("upload")}><FilePlus2 /> Upload new document</button></div></div></article>
        <article className="card"><div className="card-header"><div><p className="card-title">Integrity alerts</p><p className="card-subtitle">Review before the next transfer</p></div><span className="badge red">1 OPEN</span></div><div className="card-body"><div className="alert-list"><div className="alert-item"><span className="alert-dot" /><div><strong>Evidence_Statement_04.pdf</strong><span>Hash mismatch detected · 18 min ago</span></div><button className="btn" aria-label="Review alert">Review</button></div><div className="alert-item"><span className="alert-dot" style={{ background: "#f0b429" }} /><div><strong>Transfer approval pending</strong><span>2 documents awaiting recipient</span></div></div></div><div className="notice">Integrity alerts restrict document transfer until reviewed by an authorized officer.</div></div></article>
        <article className="card chain-card"><div className="card-header"><div><p className="card-title">Document custody chain</p><p className="card-subtitle">Evidence_Statement_03.pdf · 2.4 MB</p></div><button className="btn" onClick={() => setVerified(!verified)}><ShieldCheck /> Verify</button></div><div className="tabs">{["Case overview", "Custody chain", "Alerts"].map((item) => <button key={item} className={`tab ${tab === item ? "active" : ""}`} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === "Custody chain" || tab === "Case overview" ? <><div className="timeline">{events.map((event) => <div className="event" key={event.seq}><div className={`event-dot ${event.tone}`}>{event.tone === "green" ? <Check /> : <Fingerprint />}</div><div className="event-content"><div className="event-top"><span className="event-title">#{event.seq} <span className={`badge ${event.tone}`}>{event.action}</span></span><span className="badge gray">UTC</span></div><div className="event-meta"><span><UserRound /> {event.actor}</span><span>{event.role}</span><span>{event.time}</span></div><div className="hash"><b>SHA-256</b>{event.hash} <span>· previous: {event.prev}</span></div></div></div>)}</div><div className="integrity"><ShieldCheck className="shield" /><div><strong>{verified ? "Chain integrity verified" : "Verification pending"}</strong><span>{verified ? "All hashes match. Document is safe to transfer." : "Run verification to confirm hash continuity."}</span></div><button className="verify-btn" onClick={() => setVerified(!verified)}>{verified ? "VALID" : "VERIFY"}</button></div></> : <div className="card-body"><div className="alert-list"><div className="alert-item"><span className="alert-dot" /><div><strong>Evidence_Statement_04.pdf</strong><span>Tamper detected during verification. Document restricted.</span></div><span className="badge red">RESTRICTED</span></div></div></div>}</article></section>
      <div className="actions" style={{ justifyContent: "flex-end", marginTop: 20 }}><button className="btn" onClick={() => setModal("transfer")}><ArrowUpRight /> Request document transfer</button></div></main>
    {modal && <div className="modal-backdrop" role="presentation" onMouseDown={() => setModal(null)}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={(e) => e.stopPropagation()}><div className="card-header"><div><p className="card-title" id="modal-title">{modal === "upload" ? "Upload secured document" : "Request document transfer"}</p><p className="card-subtitle">All actions are recorded to the custody chain.</p></div><button className="close" onClick={() => setModal(null)} aria-label="Close"><X /></button></div>{modal === "upload" ? <><input ref={fileInputRef} type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={handleFileChange} hidden /><button type="button" className={`dropzone ${selectedFile ? "selected" : ""}`} onClick={() => fileInputRef.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const file = event.dataTransfer.files[0]; if (file && file.size <= 25 * 1024 * 1024) setSelectedFile(file) }}>{selectedFile ? <><FileCheck2 /><strong>{selectedFile.name}</strong><span>{(selectedFile.size / 1024 / 1024).toFixed(2)} MB selected · click to replace</span></> : <><Upload /><strong>Drop evidence files here</strong><span>or click to browse · PDF, JPG, PNG up to 25 MB</span></>}</button><div className="field"><label htmlFor="description">Document description</label><input id="description" className="field-input" placeholder="e.g. Witness statement" /></div></> : <div className="field" style={{ paddingTop: 20 }}><label htmlFor="recipient">Select recipient</label><select id="recipient"><option>Adv. Meera Shah · Public Prosecutor</option><option>Inspector Arjun Rao · Cyber Crime Unit</option><option>Dr. Neha Iyer · Digital Forensics</option></select></div>}<div className="modal-footer"><button className="btn" onClick={closeModal}>Cancel</button><button className="btn primary" onClick={modal === "upload" ? secureDocument : closeModal} disabled={modal === "upload" && !selectedFile}>{modal === "upload" ? "Secure document" : "Submit request"}</button></div></div></div>}</div>
}
